//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcDataAnnotation_validation_Test.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class MemberTable
    {
        public int Id { get; set; }
        [Required(ErrorMessage="Name required.")]
        public string Name { get; set; }
         
        [CreditCard(ErrorMessage="Give the right formate.")]
        public string creditCardNumber { get; set; }
        
        [EmailAddress(ErrorMessage="Give the right formate.")]
        public string email { get; set; }

        [Range(18,60,ErrorMessage="Age have to be 18 to 60")]
        public int age { get; set; }

        [StringLength(16,ErrorMessage="Password maximum 16 character.")]
        public string Memberpassword { get; set; }

        [Url(ErrorMessage="Give the right formate")]
        public string web { get; set; }
    }
}
